set encoding=utf-8 " Always use UTF-8
set hidden " Use hidden buffers instead of unloading buffers

""" Remove Toolbar and Menu Bars when using the GUI.
if has('gui_running') 
	set guioptions-=T " No Toolbar
	set guioptions-=m " No Menus
  set guioptions+=c " No popups, use console based prompt
  set guioptions-=r " Dont always show scrollbar
  set guioptions-=e " Dont use GUI tabs
endif

""" General text editing stuff
set tabstop=2 softtabstop=2 expandtab shiftwidth=2 smarttab " Tab stuff
set number " Show line numbers
set hlsearch
set backspace=indent,eol,start " Take care of the quirky default backspace behavior

""" Indent Stuff
set autoindent

syntax on
filetype plugin indent on

""" Select defaut color theme.
set t_Co=256
colorscheme murphy

""" Setup font depending on how gVIM is being used. Different font used on windoze
if has('gui_running')
  if has('gui_gtk2')
    set guifont=Inconsolata\ 12
  elseif has('gui_gtk3')
    set guifont=Inconsolata\ 12
  elseif has('gui_win32')
    set guifont=Consolas:h9:b:cANSI
  endif
endif

set wildmode=list:longest,full " Autocompletion

""" No line wrapping and no maximum text width by default
set nowrap " No line wrapping

""" GUI display tweaks.
if has('gui_running')
  set guitablabel=\[%N\]\ %t\ %M " Show tab number, tab name, then a if the tab was modified without saving
endif

""" Mouse
set mouse=a " Even in command line allow mouse across all modes

""" Appearance Stuff
set noshowmode " Seems redundant with vim airline
set background=dark
